bind 0.0.0.0
port 6379
protected-mode no
requirepass R3disSOC!
maxmemory 512mb
maxmemory-policy allkeys-lru
appendonly yes
appendfilename "redis-soc.aof"
appendfsync everysec
save ""
hz 15
tcp-keepalive 60
timeout 300
loglevel notice